services:

  master-bind:
    volumes:
    - ${PWD}/master/named.conf.default-zones:/etc/bind/named.conf.default-zones
    - ${PWD}/master/named.conf.options:/etc/bind/named.conf.options
    - ${PWD}/master/zones/:/etc/bind/zones/
    image: internetsystemsconsortium/bind9:9.16
    networks:
      lab:
        ipv4_address: 172.28.0.2

  slave-bind:
    volumes:
    - ${PWD}/slave/named.conf.default-zones:/etc/bind/named.conf.default-zones
    - ${PWD}/slave/named.conf.options:/etc/bind/named.conf.options
    - ${PWD}/slave/zones/:/etc/bind/zones/
    image: internetsystemsconsortium/bind9:9.16
    networks:
      lab:
        ipv4_address: 172.28.0.3

  client:
    image: alpine
    tty: true
    networks:
      lab:
        ipv4_address: 172.28.0.4

networks:
  lab:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
